name: Update Clone Stats Badge

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual runs

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Python Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python parse_clones_count.py
      
      - name: Commit and Push Badge Data
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add clone_stats.json
          git commit -m "Update clone stats badge"
          git push
